[character]

[c]
symbol = " "

[deno]
symbol = " "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[hostname]
ssh_symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Macos = " "

[python]
symbol = " "

[rust]
symbol = "󱘗 "

[swift]
symbol = " "

[zig]
symbol = " "
