if has('nvim')
  " LazyVim will handle the rest
else
  if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
  endif

  call plug#begin('~/.vim/plugged')

  Plug 'rose-pine/vim'
  Plug 'prabirshrestha/vim-lsp'
  Plug 'mattn/vim-lsp-settings'

  call plug#end()

  syntax enable
  set nu rnu ar nowrap is hls wmnu path+=** sw=2 ts=2 scl=no wim=longest:full,full wildignore+=*.o,*.obj,.git,*.pyc,*.swp,DS_Store.git,.build
  autocmd FileType markdown setlocal wrap

  let g:disable_bg = 1
  let g:disable_float_bg = 1

  function! DetectAppearance()
    let appearance = system('defaults read -g AppleInterfaceStyle 2>/dev/null')
    if v:shell_error == 0
      set background=dark
      colorscheme rosepine
    else
      set background=light
      colorscheme rosepine_dawn
    endif
  endfunction

  call DetectAppearance()
endif
